import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppHeader from "./components/AppHeader";
import AppBreadCrumb from "./components/AppBreadCrumb";
import AppMenuBodyContainer from "./components/AppMenuBodyContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader />
        <AppBreadCrumb />
        <AppMenuBodyContainer>
          {children}
        </AppMenuBodyContainer>

      </body>
    </html>
  );
}
